### ISSUE TITLE
Error if no files in project root

### ISSUE THREAD

**Issue by ukirill** [nathanjcochran/upgrade#3]
Tool runs `go list` command in the end of upgrading process. But if there is no files in module root directory (empty root package) `go list` returns exit code 1 with error _no Go files in  <module_root>_. The projects layout which contains no _.go_ files in a root are quite popular, for example [this one](https://github.com/golang-standards/project-layout).

Could we run `go list ./...` instead of `go list`?

**Comment by cochran-at-niche** [comment]
Great idea! Fixed via this commit: https://github.com/nathanjcochran/upgrade/commit/8710d328c63d05c6c449d473fa21c1da4ea1a409. Thanks for bringing this up! Sorry it took me so long to get back to you :sweat_smile:.

**Comment by nathanjcochran** [comment]
Great idea! Fixed via this commit: https://github.com/nathanjcochran/upgrade/commit/8710d328c63d05c6c449d473fa21c1da4ea1a409. Thanks for bringing this up! Sorry it took me so long to get back to you sweat_smile.
